version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: backend.dockerfile
    restart: always
    environment:
      POSTGRES_HOST: db
      MINIO_HOST: s3storage
    env_file:
      - .env
    depends_on:
      - db
      - s3storage
    ports:
      - "${APP_HOST:-localhost}:${APP_PORT:-3000}:3000"

  db:
    image: postgres:latest
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_HOST:-0.0.0.0}:${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    command: -p ${POSTGRES_PORT:-5432}

  s3storage:
    image: minio/minio:latest
    restart: always
    command: server --console-address ":${MINIO_CONSOLE_PORT:-9001}" /data
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    ports:
      - "${MINIO_HOST:-0.0.0.0}:${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_HOST:-0.0.0.0}:${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ./data/minio:/data
