"""init

Revision ID: 6f011da07daf
Revises: 
Create Date: 2022-06-15 19:11:22.830909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f011da07daf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox',
    sa.Column('request_code', postgresql.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbox')
    # ### end Alembic commands ###
